import encodings
import pandas as pd
from pyproj import get_proj_operations_map
import psycopg2

##### Lista com valores fixos #####
# Criada a partir dos comandos abaixo:

conn = psycopg2.connect(dbname='SGM',
                        user='postgres', 
                        host='ec2-3-95-135-96.compute-1.amazonaws.com',
                        password='trlab2021',                        
                        )
conn.set_client_encoding('UNICODE')

cur = conn.cursor()

cur.execute("""
           SELECT state, geoapi_id,
           COUNT(geolocation_id)
           FROM "Response"
           GROUP BY state, geoapi_id;
       """)

data_frame2 = cur.fetchall()



data_frame2 = [('AC', 'Here', 1),
('AC', 'MapBox', 5),
('AC', 'OpenRouteService', 8),
('AC', 'TomTom', 249),
('AL', 'Here', 2),
('AL', 'MapBox', 186),
('AL', 'OpenRouteService', 5),
('AL', 'TomTom', 47),
('AM', 'OpenRouteService', 8),
('AM', 'MapBox', 36),
('AM', 'TomTom', 13),
('AC', 'Here', 10),
('AC', 'MapBox', 48),
('AC', 'OpenRouteService', 18),
('AC', 'TomTom', 65),
('BA', 'Google', 2),
('BA', 'Here', 38),
('BA', 'MapBox', 654),
('BA', 'OpenRouteService', 205),
('BA', 'TomTom', 88),
('CE', 'OpenRouteService', 15),
('CE', 'Here', 8),
('CE', 'MapBox', 642),
('CE', 'TomTom', 52),
('DF', 'Google', 37),
('DF', 'TomTom', 25),
('DF', 'Google', 5),
('DF', 'MapBox', 2),
('DF', 'OpenRouteService', 32),
('ES', 'OpenRouteService', 45),
('ES', 'Google', 1),
('ES', 'Here', 30),
('ES', 'MapBox', 2226),
('ES', 'TomTom', 109),
('GO', 'OpenRouteService', 107),
('GO', 'Google', 3),
('GO', 'Here', 30),
('GO', 'MapBox', 17),
('GO', 'TomTom', 89),
('MA', 'OpenRouteService', 33),
('MA', 'Google', 3),
('MA', 'Here', 17),
('MA', 'MapBox', 68),
('MA', 'TomTom', 25),
('MT', 'Google', 3),
('MT', 'Here', 61),
('MT', 'MapBox', 218),
('MT', 'OpenRouteService', 11),
('MT', 'TomTom', 103),
('MS', 'OpenRouteService', 55),
('MS', 'Here', 1),
('MS', 'MapBox', 26),
('MS', 'TomTom', 41),
('MG', 'Google', 14),
('MG', 'Here', 36),
('MG', 'MapBox', 676),
('MG', 'OpenRouteService', 208),
('MG', 'TomTom', 166),
('PA', 'OpenRouteService', 23),
('PB', 'OpenRouteService', 7),
('PR', 'OpenRouteService', 19439),
('PR', 'Google', 28848),
('PR', 'Here', 175617),
('PR', 'MapBox', 61110),
('PR', 'TomTom', 51329),
('PB', 'Google', 18),
('PB', 'Here', 163),
('PB', 'MapBox', 199),
('PB', 'TomTom', 218),
('PA', 'Google', 2),
('PA', 'Here', 3),
('PA', 'MapBox', 54),
('PA', 'TomTom', 22),
('PE', 'Google', 5),
('PE', 'Here', 32),
('PE', 'MapBox', 617),
('PE', 'OpenRouteService', 64),
('PE', 'TomTom', 50),
('PI', 'OpenRouteService', 30),
('PI', 'Here', 2),
('PI', 'MapBox', 92),
('PI', 'TomTom', 64),
('PI', 'Google', 1),
('RJ', 'OpenRouteService', 220),
('RJ', 'Google', 9),
('RN', 'OpenRouteService', 15),
('RN', 'Google', 1),
('RN', 'Here', 4),
('RN', 'MapBox', 91),
('RN', 'TomTom', 168),
('RS', 'OpenRouteService', 19805),
('RS', 'Google', 30083),
('RS', 'Here', 175562),
('RS', 'MapBox', 67579),
('RS', 'TomTom', 53106),
('RJ', 'Google', 17),
('RJ', 'Here', 28),
('RJ', 'MapBox', 738),
('RJ', 'TomTom', 377),
('RO', 'OpenRouteService', 7),
('RO', 'Here', 3),
('RO', 'MapBox', 164),
('RO', 'TomTom', 12),
('RR', 'Here', 2),
('RR', 'MapBox', 35),
('RR', 'OpenRouteService', 2),
('SC', 'Google', 54796),
('SC', 'Here', 329355),
('SC', 'MapBox', 128838),
('SC', 'OpenRouteService', 37058),
('SC', 'TomTom', 97248),
('SP', 'OpenRouteService', 19600),
('SP', 'Google', 29028),
('SP', 'Here', 175525),
('SP', 'MapBox', 69822),
('SP', 'TomTom', 52883),
('SE', 'Google', 1),
('SE', 'Here', 1),
('SE', 'MapBox', 97),
('SE', 'OpenRouteService', 18),
('SE', 'TomTom', 36),
('TO', 'Here', 2),
('TO', 'MapBox', 16),
('TO', 'OpenRouteService', 13),
('TO', 'TomTom', 18)]

#for i in range(len(data_frame2)):
#    print(data_frame2[i])

data_frame2 = pd.DataFrame(data_frame2, columns=["state", "geoapi_id","quantities"])